version: "3.9"
services:
  temporal:
    image: ghcr.io/temporalio/temporalite:latest
    container_name: temporal
    restart: unless-stopped
    command: ["--headless"] # no UI, gRPC on 7233
    ports:
      - "7233:7233" # Temporal gRPC
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:7233"]
      interval: 10s
      timeout: 5s
      retries: 20

  temporal-ui:
    image: temporalio/ui:2.28.2
    container_name: temporal_ui
    restart: unless-stopped
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080,http://localhost:3000
    ports:
      - "8081:8080" # Temporal UI
    depends_on:
      temporal:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 20
