version: "3.9"

services:
  temporal:
    image: temporalio/auto-setup:1.25.0
    container_name: temporal
    restart: unless-stopped
    ports:
      - "7233:7233" # gRPC
    healthcheck:
      # basic TCP open check; UI health is handled by temporal-ui service
      test: ["CMD-SHELL", "bash -lc '</dev/tcp/127.0.0.1/7233'"]
      interval: 10s
      timeout: 5s
      retries: 30

  temporal-ui:
    image: temporalio/ui:2.24.0
    container_name: temporal-ui
    restart: unless-stopped
    environment:
      TEMPORAL_ADDRESS: "temporal:7233"
      TEMPORAL_GRPC_ENDPOINT: "temporal:7233"
      TEMPORAL_WEB_PORT: "${TEMPORAL_UI_PORT:-8233}"
      # Disable auth for local dev
      TEMPORAL_AUTH_ENABLED: "false"
    depends_on:
      - temporal
    ports:
      - "${TEMPORAL_UI_PORT:-8233}:8233"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8233/health | grep -q 'ok' || wget -qO- http://localhost:8233/ | grep -qi temporal"]
      interval: 10s
      timeout: 5s
      retries: 30
