version: "3.8"
services:
  temporal:
    image: temporalio/auto-setup:1.23
    environment:
      - DB=sqlite
      - DB_FILENAME=/var/lib/temporal/temporal.sqlite
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml
    ports:
      - "${TEMPORAL_GRPC_PORT:-7233}:7233"
    volumes:
      - temporal-data:/var/lib/temporal
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7233"]
      interval: 5s
      timeout: 2s
      retries: 30

volumes:
  temporal-data:

