version: "3.9"
services:
  temporal-admin:
    image: temporalio/admin-tools:1.22.2
    container_name: temporal_admin
    restart: unless-stopped
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    command: ["bash", "-lc", "tctl cluster health && tail -f /dev/null"]
    depends_on:
      temporal:
        condition: service_healthy
    profiles:
      - temporal-admin
    healthcheck:
      test: ["CMD", "tctl", "cluster", "health"]
      interval: 30s
      timeout: 10s
      retries: 10
