services:
  devcontainer:
{{#templateOption.usePrebuiltImage}}
    image: ghcr.io/airnub-labs/devcontainer-images/dev-web:latest
{{/templateOption.usePrebuiltImage}}
{{^templateOption.usePrebuiltImage}}
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
{{/templateOption.usePrebuiltImage}}
    user: "vscode"
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
  # --- Browser sidecar: Neko (WebRTC Chrome)
  neko:
    image: ghcr.io/m1k1o/neko/google-chrome:latest
    restart: unless-stopped
    ports:
      - "8080:8080"           # Neko Web UI
      - "59000:59000/tcp"     # WebRTC TCP mux (Codespaces-safe)
    environment:
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: "${NEKO_USER_PASSWORD:-student}"
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: "${NEKO_ADMIN_PASSWORD:-admin}"
      # TCP mux for proxies/Codespaces:
      NEKO_WEBRTC_TCPMUX: "59000"
      # To add STUN/TURN servers (JSON array), set:
      # NEKO_WEBRTC_ICESERVERS_FRONTEND: >-
      #   [{"urls":["stun:stun.l.google.com:19302"]}]
    # Uncomment the following for **local-only** UDP acceleration:
    # ports:
    #   - "56000-56100:56000-56100/udp"
    # environment:
    #   NEKO_WEBRTC_EPR: "56000-56100"
