name: "Bug report"
description: "Report an issue with a catalog artifact or automation"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the Devcontainers Catalog! Please share as much detail as possible so we can reproduce the issue quickly.
  - type: input
    id: artifact
    attributes:
      label: Catalog artifact
      description: Which feature, template, image, or workflow is affected?
      placeholder: e.g. features/node or images/dev-base
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the unexpected behaviour, including any failing commands or logs.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Share the precise steps or commands needed to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Runtime environment
      description: Where did you observe the issue?
      options:
        - GitHub Codespaces
        - VS Code Dev Containers
        - Docker CLI
        - Other (explain below)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs or attach screenshots if available.
      render: bash
  - type: checkboxes
    id: checklist
    attributes:
      label: Issue checklist
      options:
        - label: I have searched existing issues and documentation.
          required: true
        - label: I am willing to help verify the fix.
