blank_issues_enabled: false
contact_links:
  - name: Catalog documentation
    url: https://github.com/airnub-labs/devcontainers-catalog/tree/main/docs
    about: Review architecture, development, and security guidelines before filing an issue.
