/**
 * This file is auto-generated from schema/manifest.schema.json.
 * Do not edit this file directly. Instead, run `npm run typegen` to regenerate.
 */

export type ManifestBrowserId = 'neko-chrome' | 'neko-firefox' | 'kasm-chrome';

export type ManifestRecommendedPrivacy = 'PRIVATE' | 'COURSE' | 'PUBLIC';

export interface ManifestPort {
  port: number;
  label: string;
  purpose: string;
  recommendedPrivacy: ManifestRecommendedPrivacy;
}

export interface ManifestEnvironmentVariable {
  name: string;
  description?: string;
  required?: boolean;
}

export interface ManifestPaths {
  devcontainer: string;
  compose?: string;
  readme: string;
  classroomBrowser?: string;
}

export type ManifestCodespacesFallback = 'tcp-mux' | 'https-ws';

export interface ManifestNotes {
  prefersUDP?: boolean;
  codespacesFallback?: ManifestCodespacesFallback;
  other?: string;
}

export interface Manifest {
  schemaVersion: '1.0.0';
  stackId: string;
  catalogCommit: string;
  browsers: ManifestBrowserId[];
  ports: ManifestPort[];
  env: ManifestEnvironmentVariable[];
  paths: ManifestPaths;
  notes?: ManifestNotes;
}
