services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

  kasm-chrome:
    image: kasmweb/chrome:1.17.0
    shm_size: "2gb"
    restart: unless-stopped
    ports:
      - "6901:6901"      # HTTPS + WebSocket UI
    environment:
      # Required credential - inject via devcontainer.json "containerEnv" or Codespaces secrets
      VNC_PW: "${KASM_VNC_PW?set}"
    healthcheck:
      test: ["CMD-SHELL", "((wget --no-check-certificate -qO- https://localhost:6901/ >/dev/null 2>&1) || (curl -kfsS https://localhost:6901/ >/dev/null 2>&1) || (command -v nc >/dev/null 2>&1 && nc -z localhost 6901) || (echo >/dev/tcp/localhost/6901))"]
      interval: 10s
      timeout: 5s
      retries: 10
