services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity

  # Full Chrome via Neko (WebRTC). Defaults to TCP mux so it's Codespaces-safe.
  neko:
    image: ghcr.io/m1k1o/neko/chrome:latest
    restart: unless-stopped
    ports:
      - "8080:8080"          # Web UI
      - "59000:59000/tcp"    # WebRTC TCP mux (Codespaces compatible)
    environment:
      # Required credentials - inject via devcontainer.json "containerEnv" or Codespaces secrets
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: "${NEKO_USER_PASSWORD?set}"
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: "${NEKO_ADMIN_PASSWORD?set}"

      # Force single-port TCP mux (good for Codespaces / proxies)
      NEKO_WEBRTC_TCPMUX: "59000"

      # Classroom-friendly resolution defaults (override NEKO_SCREEN to increase fidelity)
      NEKO_SCREEN: "${NEKO_SCREEN:-1280x800@30}"

      # Supply STUN/TURN servers if you have them (JSON array). Example:
      # NEKO_WEBRTC_ICESERVERS_FRONTEND: >-
      #   [{"urls":["stun:stun.l.google.com:19302"]}]

    # Uncomment for local-only UDP acceleration (not supported in Codespaces):
    # ports:
    #   - "59000:59000/udp"
    # environment:
    #   NEKO_WEBRTC_UDPMUX: "59000"
    healthcheck:
      test: ["CMD-SHELL", "((wget -qO- http://localhost:8080/ >/dev/null 2>&1) || (curl -fsS http://localhost:8080/ >/dev/null 2>&1) || (command -v nc >/dev/null 2>&1 && nc -z localhost 8080) || (echo >/dev/tcp/localhost/8080))"]
      interval: 10s
      timeout: 3s
      retries: 10
