version: "3.8"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "${WEBTOP_HTTP_PORT:-3000}:3000"
    shm_size: "1g"
    restart: unless-stopped
    volumes:
      - ./:/work

