version: "3.8"
services:
  prefect:
    image: prefecthq/prefect:2-latest
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    ports:
      - "${PREFECT_PORT:-4200}:4200"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 3s
      retries: 30

