version: "3.9"
services:
  prefect:
    image: prefecthq/prefect:2-latest
    command: >
      bash -lc "prefect server start --host 0.0.0.0"
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_API_URL: http://prefect:4200/api
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [classroom]
networks:
  classroom: { name: classroom }
