services:
  devcontainer:
{{#templateOption.usePrebuiltImage}}
    image: ghcr.io/airnub-labs/devcontainer-images/dev-web:latest
{{/templateOption.usePrebuiltImage}}
{{^templateOption.usePrebuiltImage}}
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
{{/templateOption.usePrebuiltImage}}
    user: "vscode"
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
  # --- Browser sidecar: Kasm Chrome (KasmVNC)
  kasm-chrome:
    image: kasmweb/chrome:1.17.0
    shm_size: "2gb"
    restart: unless-stopped
    ports:
      - "6901:6901"          # HTTPS + WebSocket UI
    environment:
      VNC_PW: "${KASM_VNC_PW:-student}"
