version: "3.9"

services:
  dagster:
    image: dagster/dagster:1.7.5
    container_name: dagster
    restart: unless-stopped
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    working_dir: /opt/dagster/app
    command: bash -lc "mkdir -p /opt/dagster/dagster_home && dagster dev -h 0.0.0.0 -p ${DAGSTER_PORT:-3000}"
    ports:
      - "${DAGSTER_PORT:-3000}:3000"
    volumes:
      - dagster-home:/opt/dagster/dagster_home
      - dagster-app:/opt/dagster/app
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ | grep -qi dagster"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  dagster-home:
  dagster-app:
