version: "3.8"
services:
  dagster:
    image: dagster/dagster:1.7.20
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3001", "-w", "/opt/dagster/app/workspace.yaml"]
    ports:
      - "${DAGSTER_WEB_PORT:-3001}:3001"
    volumes:
      - ./dagster:/opt/dagster/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3001/server_info"]
      interval: 10s
      timeout: 3s
      retries: 30
