version: "3.9"
services:
  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow
    restart: unless-stopped
    environment:
      # Minimal dev: SequentialExecutor + SQLite (OK for demos)
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    command: >
      bash -lc "
        airflow db migrate &&
        airflow users create --role Admin --username admin --password admin --firstname A --lastname D --email admin@example.com || true &&
        airflow webserver
      "
    ports:
      - "8080:8080"   # Airflow UI
    volumes:
      - ./airflow:/opt/airflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 20
