version: "3.9"

services:
  airflow:
    image: apache/airflow:2.9.2
    container_name: airflow
    restart: unless-stopped
    command: bash -lc "airflow db migrate && airflow users create --username ${AIRFLOW_USER:-admin} --password ${AIRFLOW_PASSWORD:-admin} --firstname Dev --lastname User --role Admin --email admin@example.com || true && airflow webserver & airflow scheduler"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__CORE__LOAD_EXAMPLES: "${AIRFLOW_LOAD_EXAMPLES:-True}"
      _PIP_ADDITIONAL_REQUIREMENTS: "${AIRFLOW_PIP_PACKAGES:-}"
      AIRFLOW_UID: "50000"
    ports:
      - "${AIRFLOW_PORT:-8080}:8080"
    volumes:
      - airflow-dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - airflow-plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health | grep -q 'healthy'"]
      interval: 15s
      timeout: 5s
      retries: 20

volumes:
  airflow-dags:
  airflow-logs:
  airflow-plugins:
