version: "3.8"
x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__WORKERS: "2"
  _PIP_ADDITIONAL_REQUIREMENTS: ""

services:
  airflow:
    image: apache/airflow:2.10.1
    environment:
      <<: *airflow-env
    ports:
      - "${AIRFLOW_WEB_PORT:-8080}:8080"
    command: bash -lc "airflow db init && airflow users create -u admin -p admin -r Admin -e admin@example.com -f Admin -l User || true && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 30
