name: Build Preset Images

on:
  push:
    branches:
      - main
    paths:
      - "images/presets/**"
      - "Makefile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/airnub-labs/templates
  TAG: ubuntu-24.04

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - full
          - node-pnpm
          - python
          - python-prefect
          - python-airflow
          - python-dagster
          - ts-temporal
    steps:
      - uses: actions/checkout@v4

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push preset image
        env:
          PRESET: ${{ matrix.preset }}
        run: |
          devcontainer build \
            --workspace-folder images/presets/${PRESET} \
            --image-name ${REGISTRY}/${PRESET}:${TAG} \
            --platform linux/amd64,linux/arm64 \
            --push
