name: Build & Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - '.github/workflows/build-images.yml'
  workflow_dispatch: {}

jobs:
  build-dev-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push dev-base
        uses: docker/build-push-action@v6
        with:
          context: images/dev-base
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/airnub-labs/dev-base:latest
            ghcr.io/airnub-labs/dev-base:${{ github.sha }}

  build-dev-web:
    runs-on: ubuntu-latest
    needs: build-dev-base
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push dev-web
        uses: docker/build-push-action@v6
        with:
          context: images/dev-web
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/airnub-labs/dev-web:latest
            ghcr.io/airnub-labs/dev-web:${{ github.sha }}
