name: Build & Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - '.github/workflows/build-images.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - dev-base
          - dev-web
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/airnub-labs/${{ matrix.image }}:latest
