name: CD - Build & Publish Base Images
on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      TRIVY_EXIT_CODE: 0
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push dev-base
        if: ${{ hashFiles('images/dev-base/**') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: images/dev-base
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          provenance: mode=max
          sbom: true
          cache-from: type=gha,scope=dev-base
          cache-to: type=gha,mode=max,scope=dev-base
          tags: |
            ghcr.io/airnub-labs/devcontainer-images/dev-base:1.0.0
            ghcr.io/airnub-labs/devcontainer-images/dev-base:1
            ghcr.io/airnub-labs/devcontainer-images/dev-base:ubuntu-24.04
            ghcr.io/airnub-labs/devcontainer-images/dev-base:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - name: Run Trivy vulnerability scan (dev-base)
        if: ${{ hashFiles('images/dev-base/**') != '' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/airnub-labs/devcontainer-images/dev-base:latest
          format: 'sarif'
          output: trivy-dev-base.sarif
          exit-code: ${{ env.TRIVY_EXIT_CODE }}
          ignore-unfixed: true
      - name: Upload Trivy results (dev-base)
        if: ${{ hashFiles('images/dev-base/**') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-dev-base.sarif
      - name: Build & push dev-web
        if: ${{ hashFiles('images/dev-web/**') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: images/dev-web
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          provenance: mode=max
          sbom: true
          cache-from: type=gha,scope=dev-web
          cache-to: type=gha,mode=max,scope=dev-web
          tags: |
            ghcr.io/airnub-labs/devcontainer-images/dev-web:1.0.0
            ghcr.io/airnub-labs/devcontainer-images/dev-web:1
            ghcr.io/airnub-labs/devcontainer-images/dev-web:ubuntu-24.04
            ghcr.io/airnub-labs/devcontainer-images/dev-web:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - name: Run Trivy vulnerability scan (dev-web)
        if: ${{ hashFiles('images/dev-web/**') != '' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/airnub-labs/devcontainer-images/dev-web:latest
          format: 'sarif'
          output: trivy-dev-web.sarif
          exit-code: ${{ env.TRIVY_EXIT_CODE }}
          ignore-unfixed: true
      - name: Upload Trivy results (dev-web)
        if: ${{ hashFiles('images/dev-web/**') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-dev-web.sarif
