name: CI - PR Checks (Lint & Validate)

on:
  pull_request:
    paths:
      - "schemas/**"
      - "tools/generate-lesson/**"
      - "examples/lesson-manifests/**"
      - "services/**"
      - "images/presets/**"
      - "Makefile"
      - ".github/workflows/ci-pr-check.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: tools/airnub-devc/package-lock.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          python -m pip install ./tools/generate-lesson jsonschema[yaml]

      - name: Validate catalog/services.json schema
        run: npx ajv-cli@5 validate -s schemas/catalog-services.schema.json -d catalog/services.json

      - name: Run make check
        run: make check
