name: CI - Smoke Tests (Presets & Services)

on:
  pull_request:
    paths:
      - 'images/presets/**'
      - 'services/**'
      - 'tools/airnub-devc/**'
      - '.github/workflows/ci-smoke-tests.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preset-smoke:
    name: Preset smoke — ${{ matrix.preset }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - node-pnpm
          - python
          - full
          - python-prefect
          - python-airflow
          - python-dagster
          - ts-temporal
    steps:
      - uses: actions/checkout@v4

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli@0.80.1

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build preset image
        env:
          PRESET: ${{ matrix.preset }}
        run: |
          set -euo pipefail
          devcontainer build \
            --workspace-folder images/presets/${PRESET} \
            --image-name smoke-${PRESET}:ci \
            --build-arg GIT_SHA=${GITHUB_SHA}

      - name: Run preset command checks
        env:
          PRESET: ${{ matrix.preset }}
        run: |
          set -euo pipefail
          case "$PRESET" in
            node-pnpm)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "node -v && pnpm -v" ;;
            python)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "python --version" ;;
            full)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "node -v && pnpm -v && python --version" ;;
            python-prefect)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "python --version" ;;
            python-airflow)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "python --version" ;;
            python-dagster)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "python --version" ;;
            ts-temporal)
              docker run --rm --entrypoint /bin/bash smoke-${PRESET}:ci -lc "node -v && pnpm -v" ;;
            *)
              echo "Unknown preset: $PRESET" >&2
              exit 1 ;;
          esac

  service-smoke:
    name: Service fragment smoke — ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: preset-smoke
    strategy:
      fail-fast: false
      matrix:
        service:
          - redis
          - prefect
          - airflow
          - dagster
          - temporal
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Launch service fragment
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          set -euo pipefail
          case "$SERVICE" in
            redis)
              compose_args=(
                -f services/redis/docker-compose.redis.yml
              )
              check_mode="exec"
              check_service="redis"
              check_cmd=(redis-cli ping)
              ;;
            prefect)
              compose_args=(
                -f services/prefect/docker-compose.prefect.yml
              )
              check_mode="http"
              health_url="http://localhost:4200/"
              ;;
            airflow)
              compose_args=(
                -f services/airflow/docker-compose.airflow.yml
              )
              check_mode="http"
              health_url="http://localhost:8080/health"
              ;;
            dagster)
              compose_args=(
                -f services/dagster/docker-compose.dagster.yml
              )
              check_mode="http"
              health_url="http://localhost:3000/"
              ;;
            temporal)
              compose_args=(
                -f services/temporal/docker-compose.temporal.yml
              )
              check_mode="http"
              health_url="http://localhost:8081/"
              ;;
            *)
              echo "Unknown service: $SERVICE" >&2
              exit 1
              ;;
          esac

          export COMPOSE_PROJECT_NAME="smoke-${SERVICE}"
          docker compose "${compose_args[@]}" up -d

          attempt=0
          until [ $attempt -ge 18 ]; do
            if [ "$check_mode" = "http" ]; then
              if curl -fsS "$health_url" >/tmp/smoke.log 2>&1; then
                cat /tmp/smoke.log
                break
              fi
            else
              if docker compose "${compose_args[@]}" exec -T "$check_service" "${check_cmd[@]}" >/tmp/smoke.log 2>&1; then
                cat /tmp/smoke.log
                break
              fi
            fi
            attempt=$((attempt + 1))
            sleep 5
          done

          if [ $attempt -ge 18 ]; then
            echo "Service $SERVICE did not pass smoke check" >&2
            docker compose "${compose_args[@]}" logs
            exit 1
          fi

      - name: Tear down fragment
        if: always()
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          set -euo pipefail
          export COMPOSE_PROJECT_NAME="smoke-${SERVICE}"
          case "$SERVICE" in
            redis)
              compose_args=(
                -f services/redis/docker-compose.redis.yml
              )
              ;;
            prefect)
              compose_args=(
                -f services/prefect/docker-compose.prefect.yml
              )
              ;;
            airflow)
              compose_args=(
                -f services/airflow/docker-compose.airflow.yml
              )
              ;;
            dagster)
              compose_args=(
                -f services/dagster/docker-compose.dagster.yml
              )
              ;;
            temporal)
              compose_args=(
                -f services/temporal/docker-compose.temporal.yml
              )
              ;;
            *)
              exit 0
              ;;
          esac
          docker compose "${compose_args[@]}" down -v
