name: PR Checks

on:
  pull_request:
    paths:
      - "schemas/**"
      - "tools/generate-lesson/**"
      - "examples/lesson-manifests/**"
      - "services/**"
      - "images/presets/**"
      - "docs/**"
      - "Makefile"
      - "AGENTS.md"
      - ".github/workflows/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install ./tools/generate-lesson jsonschema[yaml]

      - name: Run make check
        run: make check
