name: Publish Devcontainer Features

on:
  push:
    branches: [ main ]
    paths:
      - 'features/**'
      - '.github/workflows/publish-features.yml'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/action@v1
        env:
          DEVCONTAINER_FEATURES_ALLOW_UNION_TYPES: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-features: true
          base-path-to-features: features
          oci-registry: ghcr.io
          features-namespace: airnub-labs/devcontainer-features
