name: Publish Devcontainer Features

on:
  push:
    branches: [ main ]
    paths:
      - 'features/**'
      - '.github/workflows/publish-features.yml'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          subcommand: 'features'
          args: 'publish --namespace ghcr.io/airnub-labs/devcontainer-features features'
