name: Publish Devcontainer Templates (Stacks)
on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish templates as OCI
        uses: devcontainers/action@v1
        with:
          base-path-to-templates: templates
          publish-templates: 'true'
          registry: ghcr.io
          owner: airnub-labs
          templates-namespace: devcontainer-templates
