name: Publish Devcontainer Features

on:
  push:
    branches: [ main ]
    paths:
      - 'features/**'
      - '.github/workflows/publish-features.yml'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: features
          oci-registry: ghcr.io
          features-namespace: airnub-labs/devcontainer-features
