name: Test Devcontainer Features

on:
  pull_request:
    paths:
      - 'features/**'
      - '.github/workflows/test-features.yml'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate feature schemas
        run: |
          set -euo pipefail
          for feature_dir in features/*; do
            [ -d "${feature_dir}/src" ] || continue
            echo "==> Testing feature: ${feature_dir}"
            npx --yes @devcontainers/cli@latest features test --project-folder "${feature_dir}"
          done
