name: Test Devcontainer Features

on:
  pull_request:
    paths:
      - 'features/**'
      - '.github/workflows/test-features.yml'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate feature schemas
        run: |
          npx --yes @devcontainers/cli@latest features test --skip-autofix --project-root . --features-root features
