name: Smoke Test Templates

on:
  pull_request:
    paths:
      - 'templates/**'
      - '.github/workflows/test-templates.yml'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dev Containers CLI
        run: npm i -g @devcontainers/cli@latest
      - name: Smoke test each template
        shell: bash
        run: |
          set -euo pipefail
          for T in templates/*; do
            [ -f "$T/devcontainer-template.json" ] || continue
            echo "==> Materializing template: $T"
            TMP="$(mktemp -d)"
            # Materialize into TMP using devcontainers/cli 'templates apply' once stable across environments;
            # For now, basic schema check and build a minimal payload if present.
            devcontainer templates apply --template-folder "$T" --workspace-folder "$TMP" || true
            # If template carries payload, attempt a build
            if [ -d "$T/.template/.devcontainer" ]; then
              cp -r "$T/.template/.devcontainer" "$TMP/.devcontainer"
              devcontainer build --workspace-folder "$TMP"
            fi
            rm -rf "$TMP"
          done
